# mkdocs.yml
site_name: social-links
site_description: A lightweight, zero-dependency Python library for detecting, validating, and sanitizing social media profile URLs. Supports 25+ platforms out of the box with automatic URL normalization, username extraction, and customizable regex patterns for extensibility.
site_author: Y. Siva Sai Krishna
site_url: "https://ysskrishna.github.io/social-links"
repo_name: "ysskrishna/social-links"
repo_url: "https://github.com/ysskrishna/social-links"
copyright: Copyright &copy; 2025 Y. Siva Sai Krishna
docs_dir: docs


nav:
  - Home: index.md
  - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_signature_annotations: true
            separate_signature: true
            docstring_style: google
            merge_init_into_class: true
theme:
  name: material
  locale: en
  features:
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: .

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/social-links/

    - icon: fontawesome/solid/external-link
      link: https://ysskrishna.vercel.app
    - icon: fontawesome/brands/github
      link: https://github.com/ysskrishna
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ysskrishna
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/ysskrishna

